@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.choonster.entitylivingbaseitemhandlertestmod.inventory;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;