@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.choonster.entitylivingbaseitemhandlertestmod.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;