@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.choonster.entitylivingbaseitemhandlertestmod.proxy;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;