@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.choonster.entitylivingbaseitemhandlertestmod;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;